name: Release

on:
  release:
    types: [released]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        env:
          CI: true

      - name: Set Version
        run: npm --prefix ./packages/aws-cdk-v2 version ${{ github.ref_name }}

      - name: build
        run: npm run build:aws-cdk

      - name: deploy
        run: npm publish ./dist/packages/aws-cdk-v2 --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
